const img = (file) => `${import.meta.env.BASE_URL}images/${file}`;
const nimg = (file) => `${import.meta.env.BASE_URL}images/normalized/${file.replace(/\.[^.]+$/, ".jpg")}`;

export const BRAND = {
  name: "Giftwale",
  tagline: "CREATING MEMORIES",
  slogan: "Celebrate Every Moment with the Perfect Gift!",
  phoneDisplay: "91- 70702 46161",
  phone: "917070246161",
  email: "temp@gmail.com",
  moq: 30,
  founder: {
    name: "Lakshmi Subash",
    title: "Founder",
    photo: img("founder.jpg"),
  },
};

export const COPY = {
  welcome:
    "Welcome to Giftwale, your one-stop destination for unique, creative, and memorable gifts for every occasion. We believe that every gift carries emotions, memories, and love, which is why we offer a carefully selected collection of products designed to make every moment special.",
  range:
    "From birthday gifts, anniversary surprises, and personalized items to festive hampers and corporate gifting solutions, we provide a wide range of high-quality products that suit every style and budget. Our goal is to help you find the perfect gift that brings smiles and creates unforgettable memories.",
  priority:
    "At Giftwale, customer satisfaction is our priority. We focus on quality, creativity, timely service, and unique designs to ensure every customer enjoys a smooth and delightful shopping experience. Whether you are celebrating a special occasion or simply want to make someone feel valued, we are here to make gifting more meaningful and memorable.",
  elegant:
    "Elegant personalized gifting solutions designed with luxury, love, and timeless style.",
  curated:
    "Thoughtfully curated premium gifts crafted to make every celebration memorable and special",
  handcrafted:
    "Discover handcrafted gift collections perfect for birthdays, weddings, and corporate occasions.",
};

export const CATEGORIES = [
  { id: "birthday", label: "Birthday Gift", title: "Birthday Gift", image: img("asset-10.jpg"), tone: "teal" },
  { id: "wedding", label: "Wedding Gift", title: "Wedding Gift", image: img("asset-13.png"), tone: "navy" },
  { id: "return", label: "Return Gift", title: "Return Gift", image: img("asset-12.png"), tone: "amber" },
  { id: "corporate", label: "Corporate Gift", title: "Corporate Gift", image: img("asset-02.png"), tone: "gold" },
];

export const SEARCH_HINTS = [
  { label: "Birthday Gift", q: "birthday" },
  { label: "Wedding Gift", q: "wedding" },
  { label: "Return Gift", q: "return" },
  { label: "Corporate Gift", q: "corporate" },
  { label: "Personalized", q: "personalized" },
];

export function tileSize(index) {
  return ["lg", "sm", "md", "sm", "lg", "md"][index % 6];
}

export const SERVICES = [
  {
    title: "Customized Gifting",
    icon: "ribbon",
    text: "Names, logos and messages engraved or printed so every piece feels made for the person who receives it.",
  },
  {
    title: "Corporates Gifting",
    icon: "card",
    text: "Executive hampers, desk sets and branded drinkware for client relationships and team celebrations.",
  },
  {
    title: "Whole - Sale bulk Order",
    icon: "boxes",
    text: `Call Now: ${BRAND.phoneDisplay}. Email Id - ${BRAND.email}. Moq:${BRAND.moq}`,
  },
];

export const PRODUCTS = [
  {
    id: "hopewood-hamper",
    name: "Hopewood Premium Gift Hamper",
    category: "corporate",
    image: nimg("asset-16.png"),
    blurb: COPY.elegant,
    tags: ["Luxury", "Hamper"],
  },
  {
    id: "durga-jute-bags",
    name: "Festive Jute Return Gift Bags",
    category: "return",
    image: nimg("asset-12.png"),
    blurb: COPY.handcrafted,
    tags: ["Return Gift", "Handcrafted"],
  },
  {
    id: "folk-bird-totes",
    name: "Folk Bird Canvas Tote Pair",
    category: "wedding",
    image: nimg("asset-13.png"),
    blurb: COPY.curated,
    tags: ["Wedding", "Handcrafted"],
  },
  {
    id: "paisley-pouches",
    name: "Paisley Jewellery Gift Pouches",
    category: "wedding",
    image: nimg("asset-14.png"),
    blurb: COPY.handcrafted,
    tags: ["Wedding", "Luxury"],
  },
  {
    id: "jute-window-tote",
    name: "Natural Jute Window Tote",
    category: "return",
    image: nimg("asset-11.png"),
    blurb: COPY.elegant,
    tags: ["Return Gift", "Eco"],
  },
  {
    id: "canvas-pocket-tote",
    name: "Jute & Canvas Pocket Tote",
    category: "birthday",
    image: nimg("asset-10.jpg"),
    blurb: COPY.curated,
    tags: ["Birthday", "Eco"],
  },
  {
    id: "sport-vacuum-cup",
    name: "The Best Sport Vacuum Cup",
    category: "corporate",
    image: nimg("asset-00.png"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Drinkware"],
  },
  {
    id: "smart-cup",
    name: "Smart Cup with LED Temperature Lid",
    category: "corporate",
    image: nimg("asset-01.png"),
    blurb: COPY.curated,
    tags: ["Corporate", "Tech"],
  },
  {
    id: "cork-office-set",
    name: "Cork & Chrome Corporate Desk Set",
    category: "corporate",
    image: nimg("asset-02.png"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Eco"],
  },
  {
    id: "teacher-pen-stand",
    name: "World Best Teacher Wooden Pen Set",
    category: "birthday",
    image: nimg("asset-04.png"),
    blurb: COPY.curated,
    tags: ["Birthday", "Personalized"],
  },
  {
    id: "medical-desk-set",
    name: "Personalized Medical Desk Clock Set",
    category: "corporate",
    image: nimg("asset-05.png"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Personalized"],
  },
  {
    id: "ca-desk-set",
    name: "CA Executive Gold Desk Set",
    category: "corporate",
    image: nimg("asset-07.png"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Personalized"],
  },
  {
    id: "wooden-phone-organizer",
    name: "Handcrafted Wooden Phone Organizer",
    category: "corporate",
    image: nimg("asset-08.png"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Handcrafted"],
  },
  {
    id: "house-clock-organizer",
    name: "Wooden House Clock Desk Organizer",
    category: "birthday",
    image: nimg("asset-06.png"),
    blurb: COPY.curated,
    tags: ["Birthday", "Handcrafted"],
  },
  {
    id: "led-acrylic-stand",
    name: "LED Acrylic Multi Branding Pen Stand",
    category: "corporate",
    image: nimg("asset-03.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Personalized"],
  },
  {
    id: "slatted-wood-organizer",
    name: "Two-Tone Wooden Desk Organizer",
    category: "return",
    image: nimg("asset-09.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Return Gift", "Handcrafted"],
  },
  {
    id: "corporate-gift-set-01",
    name: "Corporate Gift Set 01",
    category: "corporate",
    image: nimg("catalog/corporate-01.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-02",
    name: "Corporate Gift Set 02",
    category: "corporate",
    image: nimg("catalog/corporate-02.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-03",
    name: "Corporate Gift Set 03",
    category: "corporate",
    image: nimg("catalog/corporate-03.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-04",
    name: "Corporate Gift Set 04",
    category: "corporate",
    image: nimg("catalog/corporate-04.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-05",
    name: "Corporate Gift Set 05",
    category: "corporate",
    image: nimg("catalog/corporate-05.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-06",
    name: "Corporate Gift Set 06",
    category: "corporate",
    image: nimg("catalog/corporate-06.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-07",
    name: "Corporate Gift Set 07",
    category: "corporate",
    image: nimg("catalog/corporate-07.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-08",
    name: "Corporate Gift Set 08",
    category: "corporate",
    image: nimg("catalog/corporate-08.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-09",
    name: "Corporate Gift Set 09",
    category: "corporate",
    image: nimg("catalog/corporate-09.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-10",
    name: "Corporate Gift Set 10",
    category: "corporate",
    image: nimg("catalog/corporate-10.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-11",
    name: "Corporate Gift Set 11",
    category: "corporate",
    image: nimg("catalog/corporate-11.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-12",
    name: "Corporate Gift Set 12",
    category: "corporate",
    image: nimg("catalog/corporate-12.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-13",
    name: "Corporate Gift Set 13",
    category: "corporate",
    image: nimg("catalog/corporate-13.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-14",
    name: "Corporate Gift Set 14",
    category: "corporate",
    image: nimg("catalog/corporate-14.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-15",
    name: "Corporate Gift Set 15",
    category: "corporate",
    image: nimg("catalog/corporate-15.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-16",
    name: "Corporate Gift Set 16",
    category: "corporate",
    image: nimg("catalog/corporate-16.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-17",
    name: "Corporate Gift Set 17",
    category: "corporate",
    image: nimg("catalog/corporate-17.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-18",
    name: "Corporate Gift Set 18",
    category: "corporate",
    image: nimg("catalog/corporate-18.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-19",
    name: "Corporate Gift Set 19",
    category: "corporate",
    image: nimg("catalog/corporate-19.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-20",
    name: "Corporate Gift Set 20",
    category: "corporate",
    image: nimg("catalog/corporate-20.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-21",
    name: "Corporate Gift Set 21",
    category: "corporate",
    image: nimg("catalog/corporate-21.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-22",
    name: "Corporate Gift Set 22",
    category: "corporate",
    image: nimg("catalog/corporate-22.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-23",
    name: "Corporate Gift Set 23",
    category: "corporate",
    image: nimg("catalog/corporate-23.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-24",
    name: "Corporate Gift Set 24",
    category: "corporate",
    image: nimg("catalog/corporate-24.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-25",
    name: "Corporate Gift Set 25",
    category: "corporate",
    image: nimg("catalog/corporate-25.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-26",
    name: "Corporate Gift Set 26",
    category: "corporate",
    image: nimg("catalog/corporate-26.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-27",
    name: "Corporate Gift Set 27",
    category: "corporate",
    image: nimg("catalog/corporate-27.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "corporate-gift-set-28",
    name: "Corporate Gift Set 28",
    category: "corporate",
    image: nimg("catalog/corporate-28.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Gift Set"],
  },
  {
    id: "pride-gold-bp",
    name: "PRIDE GOLD BP",
    category: "corporate",
    image: nimg("catalog/pen-pride-gold-bp.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1263",
    name: "1263",
    category: "corporate",
    image: nimg("catalog/pen-1263.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "rani-checks",
    name: "RANI CHECKS",
    category: "corporate",
    image: nimg("catalog/pen-rani-checks.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "724-comp-r",
    name: "724 COMP R",
    category: "corporate",
    image: nimg("catalog/pen-724-comp-r.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "fuket-wood",
    name: "FUKET WOOD",
    category: "corporate",
    image: nimg("catalog/pen-fuket-wood.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "cola",
    name: "COLA",
    category: "corporate",
    image: nimg("catalog/pen-cola.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4436",
    name: "4436",
    category: "corporate",
    image: nimg("catalog/pen-4436.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "peacock",
    name: "PEACOCK",
    category: "corporate",
    image: nimg("catalog/pen-peacock.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "yono-wood",
    name: "YONO WOOD",
    category: "corporate",
    image: nimg("catalog/pen-yono-wood.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "creative-roller",
    name: "CREATIVE ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-creative-roller.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1520-roller",
    name: "1520 ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-1520-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1656-gp",
    name: "1656 GP",
    category: "corporate",
    image: nimg("catalog/pen-1656-gp.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "power-adv-bp",
    name: "POWER ADV BP",
    category: "corporate",
    image: nimg("catalog/pen-power-adv-bp.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "mono",
    name: "MONO",
    category: "corporate",
    image: nimg("catalog/pen-mono.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3600-bp",
    name: "3600 BP",
    category: "corporate",
    image: nimg("catalog/pen-3600-bp.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "727-roller",
    name: "727 ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-727-roller.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "power-roller",
    name: "POWER ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-power-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4500-adv-roller",
    name: "4500 ADV ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-4500-adv-roller.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "fortuner-beauty",
    name: "FORTUNER BEAUTY",
    category: "corporate",
    image: nimg("catalog/pen-fortuner-beauty.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "2470",
    name: "2470",
    category: "corporate",
    image: nimg("catalog/pen-2470.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "vice-president-roller",
    name: "VICE PRESIDENT ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-vice-president-roller.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3322-white",
    name: "3322 WHITE",
    category: "corporate",
    image: nimg("catalog/pen-3322-white.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "solitaire-carbon-bp",
    name: "SOLITAIRE CARBON BP",
    category: "corporate",
    image: nimg("catalog/pen-solitaire-carbon-bp.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3322-roller",
    name: "3322 ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-3322-roller.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "2450",
    name: "2450",
    category: "corporate",
    image: nimg("catalog/pen-2450.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4-q",
    name: "4 Q",
    category: "corporate",
    image: nimg("catalog/pen-4-q.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "882-beauty",
    name: "882 BEAUTY",
    category: "corporate",
    image: nimg("catalog/pen-882-beauty.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "dimension-gold",
    name: "DIMENSION GOLD",
    category: "corporate",
    image: nimg("catalog/pen-dimension-gold.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "cr77-ball-pen",
    name: "CR77 BALL PEN",
    category: "corporate",
    image: nimg("catalog/pen-cr77-ball-pen.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "nanu-23c",
    name: "NANU 23C",
    category: "corporate",
    image: nimg("catalog/pen-nanu-23c.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "mount-cement",
    name: "MOUNT CEMENT",
    category: "corporate",
    image: nimg("catalog/pen-mount-cement.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "softy-black",
    name: "SOFTY BLACK",
    category: "corporate",
    image: nimg("catalog/pen-softy-black.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "elica",
    name: "ELICA",
    category: "corporate",
    image: nimg("catalog/pen-elica.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "ns-432",
    name: "NS 432",
    category: "corporate",
    image: nimg("catalog/pen-ns-432.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "power-half-ch-bp",
    name: "POWER HALF CH BP",
    category: "corporate",
    image: nimg("catalog/pen-power-half-ch-bp.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "softy-half-satin",
    name: "SOFTY HALF SATIN",
    category: "corporate",
    image: nimg("catalog/pen-softy-half-satin.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "thar-daytime",
    name: "THAR DAYTIME",
    category: "corporate",
    image: nimg("catalog/pen-thar-daytime.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "undertaker",
    name: "UNDERTAKER",
    category: "corporate",
    image: nimg("catalog/pen-undertaker.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "fortuner-beauty-39",
    name: "FORTUNER BEAUTY 39",
    category: "corporate",
    image: nimg("catalog/pen-fortuner-beauty-39.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "duke-half-ch",
    name: "DUKE HALF CH",
    category: "corporate",
    image: nimg("catalog/pen-duke-half-ch.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "728-ball-pen",
    name: "728 BALL PEN",
    category: "corporate",
    image: nimg("catalog/pen-728-ball-pen.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "444-adv-bp",
    name: "444 ADV BP",
    category: "corporate",
    image: nimg("catalog/pen-444-adv-bp.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1459-maroon",
    name: "1459 MAROON",
    category: "corporate",
    image: nimg("catalog/pen-1459-maroon.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "targa-roller",
    name: "TARGA ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-targa-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3800-touch",
    name: "3800 TOUCH",
    category: "corporate",
    image: nimg("catalog/pen-3800-touch.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "599-nickel",
    name: "599 NICKEL",
    category: "corporate",
    image: nimg("catalog/pen-599-nickel.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "surprise-sgm-roller",
    name: "SURPRISE SGM ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-surprise-sgm-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "dimension",
    name: "DIMENSION",
    category: "corporate",
    image: nimg("catalog/pen-dimension.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "irish-twist-bp",
    name: "IRISH TWIST BP",
    category: "corporate",
    image: nimg("catalog/pen-irish-twist-bp.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "stylish-roller",
    name: "STYLISH ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-stylish-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "taj-black",
    name: "TAJ BLACK",
    category: "corporate",
    image: nimg("catalog/pen-taj-black.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "nanu-beauty",
    name: "NANU BEAUTY",
    category: "corporate",
    image: nimg("catalog/pen-nanu-beauty.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "jeep-2",
    name: "JEEP 2",
    category: "corporate",
    image: nimg("catalog/pen-jeep-2.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "cup-nickel",
    name: "CUP NICKEL",
    category: "corporate",
    image: nimg("catalog/pen-cup-nickel.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3329",
    name: "3329",
    category: "corporate",
    image: nimg("catalog/pen-3329.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "777",
    name: "777",
    category: "corporate",
    image: nimg("catalog/pen-777.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "power-adv-roller",
    name: "POWER ADV ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-power-adv-roller.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "ascend-copper-parts",
    name: "ASCEND COPPER PARTS",
    category: "corporate",
    image: nimg("catalog/pen-ascend-copper-parts.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "thrill",
    name: "THRILL",
    category: "corporate",
    image: nimg("catalog/pen-thrill.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "newton-half-gold",
    name: "NEWTON HALF GOLD",
    category: "corporate",
    image: nimg("catalog/pen-newton-half-gold.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "newton-glossy",
    name: "NEWTON GLOSSY",
    category: "corporate",
    image: nimg("catalog/pen-newton-glossy.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "supra-nickel-r",
    name: "SUPRA NICKEL R",
    category: "corporate",
    image: nimg("catalog/pen-supra-nickel-r.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "thrill-daytime",
    name: "THRILL DAYTIME",
    category: "corporate",
    image: nimg("catalog/pen-thrill-daytime.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "time-black",
    name: "TIME BLACK",
    category: "corporate",
    image: nimg("catalog/pen-time-black.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "ascend-gp",
    name: "ASCEND GP",
    category: "corporate",
    image: nimg("catalog/pen-ascend-gp.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4500-ca-roller",
    name: "4500 CA ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-4500-ca-roller.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "ruby",
    name: "RUBY",
    category: "corporate",
    image: nimg("catalog/pen-ruby.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "rudra",
    name: "RUDRA",
    category: "corporate",
    image: nimg("catalog/pen-rudra.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "savvy-rsl",
    name: "SAVVY RSL",
    category: "corporate",
    image: nimg("catalog/pen-savvy-rsl.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "paris-rose",
    name: "PARIS ROSE",
    category: "corporate",
    image: nimg("catalog/pen-paris-rose.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "paris-gold",
    name: "PARIS GOLD",
    category: "corporate",
    image: nimg("catalog/pen-paris-gold.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4500-ca-bp",
    name: "4500 CA BP",
    category: "corporate",
    image: nimg("catalog/pen-4500-ca-bp.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3800-gp",
    name: "3800 GP",
    category: "corporate",
    image: nimg("catalog/pen-3800-gp.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "quick-glossy",
    name: "QUICK GLOSSY",
    category: "corporate",
    image: nimg("catalog/pen-quick-glossy.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "rich-wood",
    name: "RICH WOOD",
    category: "corporate",
    image: nimg("catalog/pen-rich-wood.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "nanu-designer",
    name: "NANU DESIGNER",
    category: "corporate",
    image: nimg("catalog/pen-nanu-designer.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "prima",
    name: "PRIMA",
    category: "corporate",
    image: nimg("catalog/pen-prima.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "cloud-acrylic",
    name: "CLOUD ACRYLIC",
    category: "corporate",
    image: nimg("catalog/pen-cloud-acrylic.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1459-black",
    name: "1459 BLACK",
    category: "corporate",
    image: nimg("catalog/pen-1459-black.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "diana-black-roller",
    name: "DIANA BLACK ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-diana-black-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1656-bk",
    name: "1656 BK",
    category: "corporate",
    image: nimg("catalog/pen-1656-bk.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "1440",
    name: "1440",
    category: "corporate",
    image: nimg("catalog/pen-1440.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "ke-656",
    name: "KE 656",
    category: "corporate",
    image: nimg("catalog/pen-ke-656.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "figo-gold",
    name: "FIGO GOLD",
    category: "corporate",
    image: nimg("catalog/pen-figo-gold.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4500-bk-bp",
    name: "4500 BK BP",
    category: "corporate",
    image: nimg("catalog/pen-4500-bk-bp.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "2g-ashoka-emblem",
    name: "2G ASHOKA EMBLEM",
    category: "corporate",
    image: nimg("catalog/pen-2g-ashoka-emblem.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "385-indian-crystal-bk",
    name: "385 INDIAN CRYSTAL BK",
    category: "corporate",
    image: nimg("catalog/pen-385-indian-crystal-bk.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "765-roller",
    name: "765 ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-765-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "regis",
    name: "REGIS",
    category: "corporate",
    image: nimg("catalog/pen-regis.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "quill-adv-bp",
    name: "QUILL ADV BP",
    category: "corporate",
    image: nimg("catalog/pen-quill-adv-bp.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "power-fc-roller",
    name: "POWER FC ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-power-fc-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "tesla-roller",
    name: "TESLA ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-tesla-roller.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "newton-gun-metal",
    name: "NEWTON GUN METAL",
    category: "corporate",
    image: nimg("catalog/pen-newton-gun-metal.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "civic",
    name: "CIVIC",
    category: "corporate",
    image: nimg("catalog/pen-civic.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "dynamo",
    name: "DYNAMO",
    category: "corporate",
    image: nimg("catalog/pen-dynamo.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "2-x-1-coffee",
    name: "2 x 1 COFFEE",
    category: "corporate",
    image: nimg("catalog/pen-2-x-1-coffee.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "paris-silky",
    name: "PARIS SILKY",
    category: "corporate",
    image: nimg("catalog/pen-paris-silky.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "3290",
    name: "3290",
    category: "corporate",
    image: nimg("catalog/pen-3290.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "999",
    name: "999",
    category: "corporate",
    image: nimg("catalog/pen-999.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "glide-black",
    name: "GLIDE BLACK",
    category: "corporate",
    image: nimg("catalog/pen-glide-black.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "4500-magnetic",
    name: "4500 MAGNETIC",
    category: "corporate",
    image: nimg("catalog/pen-4500-magnetic.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "jupiter-gm",
    name: "JUPITER GM",
    category: "corporate",
    image: nimg("catalog/pen-jupiter-gm.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "solitaire-carbon-roller",
    name: "SOLITAIRE CARBON ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-solitaire-carbon-roller.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "nanu-gm",
    name: "NANU GM",
    category: "corporate",
    image: nimg("catalog/pen-nanu-gm.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "orient-93c",
    name: "ORIENT 93C",
    category: "corporate",
    image: nimg("catalog/pen-orient-93c.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "gp-513",
    name: "GP 513",
    category: "corporate",
    image: nimg("catalog/pen-gp-513.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "2420",
    name: "2420",
    category: "corporate",
    image: nimg("catalog/pen-2420.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "taj-metallic",
    name: "TAJ METALLIC",
    category: "corporate",
    image: nimg("catalog/pen-taj-metallic.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "110",
    name: "? 110",
    category: "corporate",
    image: nimg("catalog/pen-item-110.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "octo",
    name: "OCTO",
    category: "corporate",
    image: nimg("catalog/pen-octo.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "breeza-gold-roller",
    name: "BREEZA GOLD ROLLER",
    category: "corporate",
    image: nimg("catalog/pen-breeza-gold-roller.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-01",
    name: "Executive Pen 01",
    category: "corporate",
    image: nimg("catalog/pencat-01.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-02",
    name: "Executive Pen 02",
    category: "corporate",
    image: nimg("catalog/pencat-02.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-03",
    name: "Executive Pen 03",
    category: "corporate",
    image: nimg("catalog/pencat-03.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-04",
    name: "Executive Pen 04",
    category: "corporate",
    image: nimg("catalog/pencat-04.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-05",
    name: "Executive Pen 05",
    category: "corporate",
    image: nimg("catalog/pencat-05.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-06",
    name: "Executive Pen 06",
    category: "corporate",
    image: nimg("catalog/pencat-06.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-07",
    name: "Executive Pen 07",
    category: "corporate",
    image: nimg("catalog/pencat-07.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-08",
    name: "Executive Pen 08",
    category: "corporate",
    image: nimg("catalog/pencat-08.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-09",
    name: "Executive Pen 09",
    category: "corporate",
    image: nimg("catalog/pencat-09.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-10",
    name: "Executive Pen 10",
    category: "corporate",
    image: nimg("catalog/pencat-10.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-11",
    name: "Executive Pen 11",
    category: "corporate",
    image: nimg("catalog/pencat-11.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-12",
    name: "Executive Pen 12",
    category: "corporate",
    image: nimg("catalog/pencat-12.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-13",
    name: "Executive Pen 13",
    category: "corporate",
    image: nimg("catalog/pencat-13.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-14",
    name: "Executive Pen 14",
    category: "corporate",
    image: nimg("catalog/pencat-14.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-15",
    name: "Executive Pen 15",
    category: "corporate",
    image: nimg("catalog/pencat-15.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-16",
    name: "Executive Pen 16",
    category: "corporate",
    image: nimg("catalog/pencat-16.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-17",
    name: "Executive Pen 17",
    category: "corporate",
    image: nimg("catalog/pencat-17.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-18",
    name: "Executive Pen 18",
    category: "corporate",
    image: nimg("catalog/pencat-18.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-19",
    name: "Executive Pen 19",
    category: "corporate",
    image: nimg("catalog/pencat-19.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-20",
    name: "Executive Pen 20",
    category: "corporate",
    image: nimg("catalog/pencat-20.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-21",
    name: "Executive Pen 21",
    category: "corporate",
    image: nimg("catalog/pencat-21.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-22",
    name: "Executive Pen 22",
    category: "corporate",
    image: nimg("catalog/pencat-22.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-23",
    name: "Executive Pen 23",
    category: "corporate",
    image: nimg("catalog/pencat-23.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-24",
    name: "Executive Pen 24",
    category: "corporate",
    image: nimg("catalog/pencat-24.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-25",
    name: "Executive Pen 25",
    category: "corporate",
    image: nimg("catalog/pencat-25.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-26",
    name: "Executive Pen 26",
    category: "corporate",
    image: nimg("catalog/pencat-26.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-27",
    name: "Executive Pen 27",
    category: "corporate",
    image: nimg("catalog/pencat-27.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-28",
    name: "Executive Pen 28",
    category: "corporate",
    image: nimg("catalog/pencat-28.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-29",
    name: "Executive Pen 29",
    category: "corporate",
    image: nimg("catalog/pencat-29.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-30",
    name: "Executive Pen 30",
    category: "corporate",
    image: nimg("catalog/pencat-30.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-31",
    name: "Executive Pen 31",
    category: "corporate",
    image: nimg("catalog/pencat-31.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-32",
    name: "Executive Pen 32",
    category: "corporate",
    image: nimg("catalog/pencat-32.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-33",
    name: "Executive Pen 33",
    category: "corporate",
    image: nimg("catalog/pencat-33.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-34",
    name: "Executive Pen 34",
    category: "corporate",
    image: nimg("catalog/pencat-34.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-35",
    name: "Executive Pen 35",
    category: "corporate",
    image: nimg("catalog/pencat-35.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-36",
    name: "Executive Pen 36",
    category: "corporate",
    image: nimg("catalog/pencat-36.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-37",
    name: "Executive Pen 37",
    category: "corporate",
    image: nimg("catalog/pencat-37.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-38",
    name: "Executive Pen 38",
    category: "corporate",
    image: nimg("catalog/pencat-38.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-39",
    name: "Executive Pen 39",
    category: "corporate",
    image: nimg("catalog/pencat-39.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-40",
    name: "Executive Pen 40",
    category: "corporate",
    image: nimg("catalog/pencat-40.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-41",
    name: "Executive Pen 41",
    category: "corporate",
    image: nimg("catalog/pencat-41.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-42",
    name: "Executive Pen 42",
    category: "corporate",
    image: nimg("catalog/pencat-42.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-43",
    name: "Executive Pen 43",
    category: "corporate",
    image: nimg("catalog/pencat-43.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-44",
    name: "Executive Pen 44",
    category: "corporate",
    image: nimg("catalog/pencat-44.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-45",
    name: "Executive Pen 45",
    category: "corporate",
    image: nimg("catalog/pencat-45.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-46",
    name: "Executive Pen 46",
    category: "corporate",
    image: nimg("catalog/pencat-46.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-47",
    name: "Executive Pen 47",
    category: "corporate",
    image: nimg("catalog/pencat-47.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-48",
    name: "Executive Pen 48",
    category: "corporate",
    image: nimg("catalog/pencat-48.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-49",
    name: "Executive Pen 49",
    category: "corporate",
    image: nimg("catalog/pencat-49.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-50",
    name: "Executive Pen 50",
    category: "corporate",
    image: nimg("catalog/pencat-50.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-51",
    name: "Executive Pen 51",
    category: "corporate",
    image: nimg("catalog/pencat-51.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-52",
    name: "Executive Pen 52",
    category: "corporate",
    image: nimg("catalog/pencat-52.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-53",
    name: "Executive Pen 53",
    category: "corporate",
    image: nimg("catalog/pencat-53.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-54",
    name: "Executive Pen 54",
    category: "corporate",
    image: nimg("catalog/pencat-54.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-55",
    name: "Executive Pen 55",
    category: "corporate",
    image: nimg("catalog/pencat-55.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-56",
    name: "Executive Pen 56",
    category: "corporate",
    image: nimg("catalog/pencat-56.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-57",
    name: "Executive Pen 57",
    category: "corporate",
    image: nimg("catalog/pencat-57.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-58",
    name: "Executive Pen 58",
    category: "corporate",
    image: nimg("catalog/pencat-58.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-59",
    name: "Executive Pen 59",
    category: "corporate",
    image: nimg("catalog/pencat-59.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-60",
    name: "Executive Pen 60",
    category: "corporate",
    image: nimg("catalog/pencat-60.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-61",
    name: "Executive Pen 61",
    category: "corporate",
    image: nimg("catalog/pencat-61.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-62",
    name: "Executive Pen 62",
    category: "corporate",
    image: nimg("catalog/pencat-62.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-63",
    name: "Executive Pen 63",
    category: "corporate",
    image: nimg("catalog/pencat-63.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-64",
    name: "Executive Pen 64",
    category: "corporate",
    image: nimg("catalog/pencat-64.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-65",
    name: "Executive Pen 65",
    category: "corporate",
    image: nimg("catalog/pencat-65.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-66",
    name: "Executive Pen 66",
    category: "corporate",
    image: nimg("catalog/pencat-66.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-67",
    name: "Executive Pen 67",
    category: "corporate",
    image: nimg("catalog/pencat-67.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-68",
    name: "Executive Pen 68",
    category: "corporate",
    image: nimg("catalog/pencat-68.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-69",
    name: "Executive Pen 69",
    category: "corporate",
    image: nimg("catalog/pencat-69.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-70",
    name: "Executive Pen 70",
    category: "corporate",
    image: nimg("catalog/pencat-70.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-71",
    name: "Executive Pen 71",
    category: "corporate",
    image: nimg("catalog/pencat-71.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-72",
    name: "Executive Pen 72",
    category: "corporate",
    image: nimg("catalog/pencat-72.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-73",
    name: "Executive Pen 73",
    category: "corporate",
    image: nimg("catalog/pencat-73.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-74",
    name: "Executive Pen 74",
    category: "corporate",
    image: nimg("catalog/pencat-74.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-75",
    name: "Executive Pen 75",
    category: "corporate",
    image: nimg("catalog/pencat-75.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-76",
    name: "Executive Pen 76",
    category: "corporate",
    image: nimg("catalog/pencat-76.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-77",
    name: "Executive Pen 77",
    category: "corporate",
    image: nimg("catalog/pencat-77.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-78",
    name: "Executive Pen 78",
    category: "corporate",
    image: nimg("catalog/pencat-78.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-79",
    name: "Executive Pen 79",
    category: "corporate",
    image: nimg("catalog/pencat-79.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-80",
    name: "Executive Pen 80",
    category: "corporate",
    image: nimg("catalog/pencat-80.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-81",
    name: "Executive Pen 81",
    category: "corporate",
    image: nimg("catalog/pencat-81.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-82",
    name: "Executive Pen 82",
    category: "corporate",
    image: nimg("catalog/pencat-82.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-83",
    name: "Executive Pen 83",
    category: "corporate",
    image: nimg("catalog/pencat-83.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-84",
    name: "Executive Pen 84",
    category: "corporate",
    image: nimg("catalog/pencat-84.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-85",
    name: "Executive Pen 85",
    category: "corporate",
    image: nimg("catalog/pencat-85.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-86",
    name: "Executive Pen 86",
    category: "corporate",
    image: nimg("catalog/pencat-86.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-87",
    name: "Executive Pen 87",
    category: "corporate",
    image: nimg("catalog/pencat-87.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-88",
    name: "Executive Pen 88",
    category: "corporate",
    image: nimg("catalog/pencat-88.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-89",
    name: "Executive Pen 89",
    category: "corporate",
    image: nimg("catalog/pencat-89.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-90",
    name: "Executive Pen 90",
    category: "corporate",
    image: nimg("catalog/pencat-90.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-91",
    name: "Executive Pen 91",
    category: "corporate",
    image: nimg("catalog/pencat-91.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-92",
    name: "Executive Pen 92",
    category: "corporate",
    image: nimg("catalog/pencat-92.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-93",
    name: "Executive Pen 93",
    category: "corporate",
    image: nimg("catalog/pencat-93.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-94",
    name: "Executive Pen 94",
    category: "corporate",
    image: nimg("catalog/pencat-94.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-95",
    name: "Executive Pen 95",
    category: "corporate",
    image: nimg("catalog/pencat-95.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-96",
    name: "Executive Pen 96",
    category: "corporate",
    image: nimg("catalog/pencat-96.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-97",
    name: "Executive Pen 97",
    category: "corporate",
    image: nimg("catalog/pencat-97.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-98",
    name: "Executive Pen 98",
    category: "corporate",
    image: nimg("catalog/pencat-98.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-99",
    name: "Executive Pen 99",
    category: "corporate",
    image: nimg("catalog/pencat-99.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-100",
    name: "Executive Pen 100",
    category: "corporate",
    image: nimg("catalog/pencat-100.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-101",
    name: "Executive Pen 101",
    category: "corporate",
    image: nimg("catalog/pencat-101.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-102",
    name: "Executive Pen 102",
    category: "corporate",
    image: nimg("catalog/pencat-102.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-103",
    name: "Executive Pen 103",
    category: "corporate",
    image: nimg("catalog/pencat-103.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-104",
    name: "Executive Pen 104",
    category: "corporate",
    image: nimg("catalog/pencat-104.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-105",
    name: "Executive Pen 105",
    category: "corporate",
    image: nimg("catalog/pencat-105.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-106",
    name: "Executive Pen 106",
    category: "corporate",
    image: nimg("catalog/pencat-106.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-107",
    name: "Executive Pen 107",
    category: "corporate",
    image: nimg("catalog/pencat-107.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-108",
    name: "Executive Pen 108",
    category: "corporate",
    image: nimg("catalog/pencat-108.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-109",
    name: "Executive Pen 109",
    category: "corporate",
    image: nimg("catalog/pencat-109.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-110",
    name: "Executive Pen 110",
    category: "corporate",
    image: nimg("catalog/pencat-110.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-111",
    name: "Executive Pen 111",
    category: "corporate",
    image: nimg("catalog/pencat-111.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-112",
    name: "Executive Pen 112",
    category: "corporate",
    image: nimg("catalog/pencat-112.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-113",
    name: "Executive Pen 113",
    category: "corporate",
    image: nimg("catalog/pencat-113.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-114",
    name: "Executive Pen 114",
    category: "corporate",
    image: nimg("catalog/pencat-114.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-115",
    name: "Executive Pen 115",
    category: "corporate",
    image: nimg("catalog/pencat-115.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-116",
    name: "Executive Pen 116",
    category: "corporate",
    image: nimg("catalog/pencat-116.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-117",
    name: "Executive Pen 117",
    category: "corporate",
    image: nimg("catalog/pencat-117.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-118",
    name: "Executive Pen 118",
    category: "corporate",
    image: nimg("catalog/pencat-118.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-119",
    name: "Executive Pen 119",
    category: "corporate",
    image: nimg("catalog/pencat-119.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-120",
    name: "Executive Pen 120",
    category: "corporate",
    image: nimg("catalog/pencat-120.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-121",
    name: "Executive Pen 121",
    category: "corporate",
    image: nimg("catalog/pencat-121.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-122",
    name: "Executive Pen 122",
    category: "corporate",
    image: nimg("catalog/pencat-122.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-123",
    name: "Executive Pen 123",
    category: "corporate",
    image: nimg("catalog/pencat-123.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-124",
    name: "Executive Pen 124",
    category: "corporate",
    image: nimg("catalog/pencat-124.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-125",
    name: "Executive Pen 125",
    category: "corporate",
    image: nimg("catalog/pencat-125.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-126",
    name: "Executive Pen 126",
    category: "corporate",
    image: nimg("catalog/pencat-126.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-127",
    name: "Executive Pen 127",
    category: "corporate",
    image: nimg("catalog/pencat-127.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-128",
    name: "Executive Pen 128",
    category: "corporate",
    image: nimg("catalog/pencat-128.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-129",
    name: "Executive Pen 129",
    category: "corporate",
    image: nimg("catalog/pencat-129.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-130",
    name: "Executive Pen 130",
    category: "corporate",
    image: nimg("catalog/pencat-130.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-131",
    name: "Executive Pen 131",
    category: "corporate",
    image: nimg("catalog/pencat-131.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-132",
    name: "Executive Pen 132",
    category: "corporate",
    image: nimg("catalog/pencat-132.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-133",
    name: "Executive Pen 133",
    category: "corporate",
    image: nimg("catalog/pencat-133.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-134",
    name: "Executive Pen 134",
    category: "corporate",
    image: nimg("catalog/pencat-134.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-135",
    name: "Executive Pen 135",
    category: "corporate",
    image: nimg("catalog/pencat-135.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-136",
    name: "Executive Pen 136",
    category: "corporate",
    image: nimg("catalog/pencat-136.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-137",
    name: "Executive Pen 137",
    category: "corporate",
    image: nimg("catalog/pencat-137.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-138",
    name: "Executive Pen 138",
    category: "corporate",
    image: nimg("catalog/pencat-138.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-139",
    name: "Executive Pen 139",
    category: "corporate",
    image: nimg("catalog/pencat-139.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-140",
    name: "Executive Pen 140",
    category: "corporate",
    image: nimg("catalog/pencat-140.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-141",
    name: "Executive Pen 141",
    category: "corporate",
    image: nimg("catalog/pencat-141.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-142",
    name: "Executive Pen 142",
    category: "corporate",
    image: nimg("catalog/pencat-142.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-143",
    name: "Executive Pen 143",
    category: "corporate",
    image: nimg("catalog/pencat-143.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-144",
    name: "Executive Pen 144",
    category: "corporate",
    image: nimg("catalog/pencat-144.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-145",
    name: "Executive Pen 145",
    category: "corporate",
    image: nimg("catalog/pencat-145.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-146",
    name: "Executive Pen 146",
    category: "corporate",
    image: nimg("catalog/pencat-146.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-147",
    name: "Executive Pen 147",
    category: "corporate",
    image: nimg("catalog/pencat-147.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-148",
    name: "Executive Pen 148",
    category: "corporate",
    image: nimg("catalog/pencat-148.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-149",
    name: "Executive Pen 149",
    category: "corporate",
    image: nimg("catalog/pencat-149.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-150",
    name: "Executive Pen 150",
    category: "corporate",
    image: nimg("catalog/pencat-150.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-151",
    name: "Executive Pen 151",
    category: "corporate",
    image: nimg("catalog/pencat-151.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-152",
    name: "Executive Pen 152",
    category: "corporate",
    image: nimg("catalog/pencat-152.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-153",
    name: "Executive Pen 153",
    category: "corporate",
    image: nimg("catalog/pencat-153.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-154",
    name: "Executive Pen 154",
    category: "corporate",
    image: nimg("catalog/pencat-154.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-155",
    name: "Executive Pen 155",
    category: "corporate",
    image: nimg("catalog/pencat-155.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-156",
    name: "Executive Pen 156",
    category: "corporate",
    image: nimg("catalog/pencat-156.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-157",
    name: "Executive Pen 157",
    category: "corporate",
    image: nimg("catalog/pencat-157.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-158",
    name: "Executive Pen 158",
    category: "corporate",
    image: nimg("catalog/pencat-158.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-159",
    name: "Executive Pen 159",
    category: "corporate",
    image: nimg("catalog/pencat-159.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-160",
    name: "Executive Pen 160",
    category: "corporate",
    image: nimg("catalog/pencat-160.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-161",
    name: "Executive Pen 161",
    category: "corporate",
    image: nimg("catalog/pencat-161.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-162",
    name: "Executive Pen 162",
    category: "corporate",
    image: nimg("catalog/pencat-162.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-163",
    name: "Executive Pen 163",
    category: "corporate",
    image: nimg("catalog/pencat-163.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-164",
    name: "Executive Pen 164",
    category: "corporate",
    image: nimg("catalog/pencat-164.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-165",
    name: "Executive Pen 165",
    category: "corporate",
    image: nimg("catalog/pencat-165.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-166",
    name: "Executive Pen 166",
    category: "corporate",
    image: nimg("catalog/pencat-166.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-167",
    name: "Executive Pen 167",
    category: "corporate",
    image: nimg("catalog/pencat-167.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-168",
    name: "Executive Pen 168",
    category: "corporate",
    image: nimg("catalog/pencat-168.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-169",
    name: "Executive Pen 169",
    category: "corporate",
    image: nimg("catalog/pencat-169.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-170",
    name: "Executive Pen 170",
    category: "corporate",
    image: nimg("catalog/pencat-170.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-171",
    name: "Executive Pen 171",
    category: "corporate",
    image: nimg("catalog/pencat-171.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-172",
    name: "Executive Pen 172",
    category: "corporate",
    image: nimg("catalog/pencat-172.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-173",
    name: "Executive Pen 173",
    category: "corporate",
    image: nimg("catalog/pencat-173.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-174",
    name: "Executive Pen 174",
    category: "corporate",
    image: nimg("catalog/pencat-174.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-175",
    name: "Executive Pen 175",
    category: "corporate",
    image: nimg("catalog/pencat-175.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-176",
    name: "Executive Pen 176",
    category: "corporate",
    image: nimg("catalog/pencat-176.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-177",
    name: "Executive Pen 177",
    category: "corporate",
    image: nimg("catalog/pencat-177.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-178",
    name: "Executive Pen 178",
    category: "corporate",
    image: nimg("catalog/pencat-178.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-179",
    name: "Executive Pen 179",
    category: "corporate",
    image: nimg("catalog/pencat-179.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-180",
    name: "Executive Pen 180",
    category: "corporate",
    image: nimg("catalog/pencat-180.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-181",
    name: "Executive Pen 181",
    category: "corporate",
    image: nimg("catalog/pencat-181.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-182",
    name: "Executive Pen 182",
    category: "corporate",
    image: nimg("catalog/pencat-182.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-183",
    name: "Executive Pen 183",
    category: "corporate",
    image: nimg("catalog/pencat-183.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-184",
    name: "Executive Pen 184",
    category: "corporate",
    image: nimg("catalog/pencat-184.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-185",
    name: "Executive Pen 185",
    category: "corporate",
    image: nimg("catalog/pencat-185.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-186",
    name: "Executive Pen 186",
    category: "corporate",
    image: nimg("catalog/pencat-186.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-187",
    name: "Executive Pen 187",
    category: "corporate",
    image: nimg("catalog/pencat-187.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-188",
    name: "Executive Pen 188",
    category: "corporate",
    image: nimg("catalog/pencat-188.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-189",
    name: "Executive Pen 189",
    category: "corporate",
    image: nimg("catalog/pencat-189.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-190",
    name: "Executive Pen 190",
    category: "corporate",
    image: nimg("catalog/pencat-190.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-191",
    name: "Executive Pen 191",
    category: "corporate",
    image: nimg("catalog/pencat-191.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-192",
    name: "Executive Pen 192",
    category: "corporate",
    image: nimg("catalog/pencat-192.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-193",
    name: "Executive Pen 193",
    category: "corporate",
    image: nimg("catalog/pencat-193.jpg"),
    blurb: COPY.handcrafted,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-194",
    name: "Executive Pen 194",
    category: "corporate",
    image: nimg("catalog/pencat-194.jpg"),
    blurb: COPY.elegant,
    tags: ["Corporate", "Pen"],
  },
  {
    id: "executive-pen-195",
    name: "Executive Pen 195",
    category: "corporate",
    image: nimg("catalog/pencat-195.jpg"),
    blurb: COPY.curated,
    tags: ["Corporate", "Pen"],
  }
];
